# Generated by Django 4.1.2 on 2022-10-18 20:07

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_info', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=11)),
                ('country', models.PositiveIntegerField(choices=[(0, 'Turkey'), (1, 'Others')])),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('cv', models.FileField(upload_to='CVs')),
                ('school', models.CharField(max_length=255)),
                ('graduate_year', models.PositiveIntegerField()),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, size=None)),
                ('status', models.PositiveIntegerField(choices=[(0, 'Full Time'), (1, 'Part Time'), (2, 'Intern'), (3, 'Remote')], default=0)),
                ('applications', models.ManyToManyField(to='account.applications')),
            ],
        ),
    ]
