# Generated by Django 4.1.2 on 2022-10-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='applications',
            field=models.ManyToManyField(blank=True, to='account.applications'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('Turkey', 'Turkey'), ('Others', 'Others')], max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Intern', 'Intern'), ('Remote', 'Remote')], default=0, max_length=255),
        ),
    ]
