# Generated by Django 4.1.2 on 2022-10-19 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_applications_alter_profile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 10, 19, 16, 30, 6, 820105)),
        ),
    ]
