# Generated by Django 4.1.2 on 2022-10-19 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_remove_applicants_applicant_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_remove_applications_applicant_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='applications',
        ),
        migrations.AddField(
            model_name='applications',
            name='applicant_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='applicant_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applications',
            name='applied_job',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='applied_job', to='jobapp.job'),
        ),
    ]
