# Generated by Django 4.1.2 on 2022-10-18 20:07

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=150)),
                ('country', models.PositiveIntegerField(choices=[(0, 'Turkey'), (1, 'Others')])),
                ('status', models.PositiveIntegerField(choices=[(0, 'Full Time'), (1, 'Part Time'), (2, 'Intern'), (3, 'Remote')], default=0)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('require_skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), size=None)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('applicants', models.ManyToManyField(to='jobapp.applicants')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
